fileobj=open("text2.txt","w")
fileobj.write("ic")
fileobj.close()
fileobj=open("text2.txt","a")
fileobj.write("1234")
username=input("eneter the name")
password=input("enyter the password")
fileobj=open("text2.txt","r")
uname=fileobj.readline()
upass=fileobj.readline()
print (username)
print (password)
print(uname)
print(upass)
uname=uname.rstrip("\n") 
if username==uname and password==upass:
    print ("successfull")
else:
    print ("invalid")