fileobj=open("text3.txt","w")
fileobj.write("ic\n")
fileobj.close()
fileobj=open("text3.txt","a")
fileobj.write("1234")
fileobj.close()
username=input("eneter the name")
password=input("enter the password")
fileobj=open("text3.txt","r")
uname=fileobj.readline()
upass=fileobj.readline()
print (username)
print (password)
print (uname)
print (upass)
uname=uname.rstrip("\n") 
if username==uname and password==upass:
    print ("successfull")
else:
    print ("invalid")